"""user-table

Revision ID: dcd03c9fce6b
Revises: 
Create Date: 2025-06-14 14:18:28.261519

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.core.config.settings import settings
from src.infrastructure.database.models.user import UserRole
from src.routes.auth.utils import password_util

# revision identifiers, used by Alembic.
revision: str = 'dcd03c9fce6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('username', sa.String(length=50), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('role', sa.Enum('admin', 'user', 'staff', name='role', create_constraint=True),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    admin_username = 'admin'
    admin_email = settings.admin_data.ADMIN_EMAIL
    admin_password = password_util.hash_password(settings.admin_data.ADMIN_PASSWORD)
    admin_role = UserRole.admin.value
    now = datetime.utcnow()

    op.execute(
        f"""
            INSERT INTO users (username, email, password, role, created_at, updated_at)
            VALUES (
                '{admin_username}',
                '{admin_email}',
                '{admin_password}',
                '{admin_role}',
                '{now}',
                '{now}'
            )
            """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute("DROP TYPE role;")
    # ### end Alembic commands ###
