"""vacancy table

Revision ID: a5a432359f77
Revises: d84e029c9631
Create Date: 2025-10-18 22:55:24.051559

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a432359f77'
down_revision: Union[str, Sequence[str], None] = 'd84e029c9631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DROP TYPE IF EXISTS vacancystatus;")
    op.execute("DROP TYPE IF EXISTS educationlevel;")
    op.execute("DROP TYPE IF EXISTS applicationstatus;")
    op.execute("DROP TYPE IF EXISTS employmentform;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PAUSED', name='vacancystatus'), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String), nullable=True),
    sa.Column('education', sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'PHD', 'ANY', name='educationlevel'), nullable=True, server_default='ANY'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('employment_form', sa.Enum('FULL_TIME', 'PART_TIME', 'REMOTE',name='employmentform'),nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hr_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_id'), 'vacancies', ['id'], unique=False)
    op.create_table('vacancy_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_applications_id'), 'vacancy_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_applications_id'), table_name='vacancy_applications')
    op.drop_table('vacancy_applications')
    op.drop_index(op.f('ix_vacancies_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.execute("DROP TYPE IF EXISTS vacancystatus;")
    op.execute("DROP TYPE IF EXISTS educationlevel;")
    op.execute("DROP TYPE IF EXISTS applicationstatus;")
    op.execute("DROP TYPE IF EXISTS employmentform;")
    # ### end Alembic commands ###
