"""User table

Revision ID: d84e029c9631
Revises: 
Create Date: 2025-10-18 17:39:03.160571

"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from src.config import settings
from src.models.user import UserRole
from src.api_v1.auth.utils import password_util

# revision identifiers, used by Alembic.
revision: str = 'd84e029c9631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'hr', name='role', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

    admin_email = settings.admin_data.ADMIN_EMAIL
    admin_password = password_util.hash_password(settings.admin_data.ADMIN_PASSWORD)
    admin_role = UserRole.admin.value
    now = datetime.utcnow()

    op.execute(
        f"""
        INSERT INTO "user" (first_name,last_name, email, password, role, created_at, updated_at)
        VALUES (
            'Sanzhar',
            'Konysbayev',
            '{admin_email}',
            '{admin_password}',
            '{admin_role}',
            '{now}',
            '{now}'
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.execute("DROP TYPE role;")
    # ### end Alembic commands ###
